criado a emptyView
devpass-tech/challenge-viewcode-realestate pull request #25
Opened 2021-12-07 20:23 UTC by TatianaRico

2021-12-07 22:23 UTC, rdgborges requested changes
Está acontecendo aquele problema pois as suas labels não estão iniciadas. Eu adicionei 2 comentários sobre isso. :)

2021-12-07 22:23 UTC, rdgborges commented on solutions/devsprint-viewcode-3/ViewCodeChallenge-RealEstate/Screens/EmptyView.swift
> +    private var titleText: UILabel {
Aqui faltou utilizar o padrão "closure init" para inicializar corretamente a UILabel:

```swift
private var titleText: UILabel = {
    let lb = UILabel()
    //...
    return lb
}()
```

2021-12-07 22:23 UTC, rdgborges commented on solutions/devsprint-viewcode-3/ViewCodeChallenge-RealEstate/Screens/EmptyView.swift
> +    private var msgText: UILabel {
Aqui faltou utilizar o padrão "closure init" para inicializar corretamente a UILabel:

```swift
private var msgText: UILabel = {
    let lb = UILabel()
    //...
    return lb
}()
```

2021-12-08 12:38 UTC, TatianaRico commented
![Captura de Tela 2021-12-07 às 19 27 56](https://user-images.githubusercontent.com/55116105/145209685-35123467-e7fd-4cc0-b279-54a884713f10.png)

2021-12-08 17:56 UTC, rdgborges requested changes
Parabéns Tatiana! 👏  Só precisamos que use o padrão com o protocolo `ViewCode` para a configuração interna da EmptyView.

2021-12-08 17:56 UTC, rdgborges commented on solutions/devsprint-viewcode-3/ViewCodeChallenge-RealEstate/Screens/EmptyView.swift
> +        setupView()
Em vez de criar os métodos `setupView()`, `setupAddView()` e `setupContrains()`, devemos conformar a classe EmptyView com o protocolo `ViewCode`. A partir disso, você utiliza os métodos do protocolo para fazer as configurações internas da EmptyView.

```swift
extension EmptyView: ViewCode {
//...
}
```

2021-12-08 17:58 UTC, rdgborges requested changes
Além disso, é necessário implementar um teste de snapshot para a EmptyView.

2021-12-08 22:04 UTC, rdgborges requested changes

2021-12-08 22:04 UTC, rdgborges commented on solutions/devsprint-viewcode-3/ViewCodeChallenge-RealEstate/Screens/EmptyView.swift
> +    public func updateTextView(msg: EmptyViewConfiguration) {
Alterar nome do método para `func configure(with configuration: EmptyViewConfiguration)` para seguir o padrão que temos utilizado.

Obs: Alterando o nome do método aqui, você terá que alterar no arquivo do teste de snapshot também.

2021-12-09 20:54 UTC, rdgborges approved these changes

2021-12-09 21:12 UTC, merged