Implementa LoginView ✨
devpass-tech/challenge-viewcode-realestate pull request #70
Opened 2022-05-11 18:39 UTC by luiza-cora

### Descrição simples da nova feature
 
Tela de Login do aplicativo.
 
### Checklist:
Coloque um ```x``` nas caixas que se aplicam.
- [x] Não adiciona código duplicado
- [x] Não contém código comentado
- [x] Não contém código WIP
 
### Evidências da feature:

2022-05-11 20:18 UTC, reisdev requested changes

2022-05-11 20:18 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateApp/AppDelegate/SceneDelegate.swift
> +        self.window?.rootViewController = UINavigationController(rootViewController: AccountViewController())
Você fez essa modificação apenas para teste, correto? Se sim, sugiro retornar ao estado anterior, com a `PropertyListViewController`

```suggestion
        self.window?.rootViewController = UINavigationController(rootViewController: PropertyListViewController())
```

2022-05-11 20:35 UTC, luiza-cora commented on solutions/devsprint-matheus-reis-1/RealEstateApp/AppDelegate/SceneDelegate.swift
> +        self.window?.rootViewController = UINavigationController(rootViewController: AccountViewController())
fiz, mas foi proposital, a tela de login nao seria a primeira do app?

2022-05-12 13:22 UTC, luiza-cora commented
Conflitos resolvidos

2022-05-12 13:41 UTC, reisdev approved these changes

2022-05-12 13:41 UTC, merged