Feature/implementar loading view✨
devpass-tech/challenge-viewcode-realestate pull request #72
Opened 2022-05-11 19:29 UTC by marianamai

### Descrição simples da nova feature:
O LoadingView é um componente de interface que mostra um título e um UIActivityIndicator centralizados.
 
### Checklist:
- [x]  Implementar componente no arquivo LoadingView.swift
- [x]  A LoadingView terá um UILabel e um UIActivityIndicator centralizados na tela como subviews
- [x]  A Loading View não deve ser integrada a uma tela
- [x]  Implementar Teste de Snapshot para o componente

2022-05-11 19:29 UTC, marianamai commented
🥲

2022-05-11 20:22 UTC, reisdev requested changes

2022-05-11 20:22 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateApp/UI/Components/LoadingView.swift
> +        indicator.startAnimating()
Para evitar consumir recurso desnecessariamente, não é interessante chamar o `startAnimating` . Uma possibilidade seria criar um método que alterna a animação, iniciando e parando de animar programaticamente .

2022-05-11 20:22 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateAppTests/Components/LoadingViewTest.swift
> +    override func setUpWithError() throws {
Como este método não é utilizado, ele pode ser removido

2022-05-11 20:22 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateAppTests/Components/LoadingViewTest.swift
> +    func testDividerView() {
O nome do teste ficou como `testDividerView`, imagino que tenha replicado o arquivo e faltou fazer essa alteração.
```suggestion
    func testLoadingView() {
```

2022-05-12 14:48 UTC, reisdev approved these changes

2022-05-12 14:50 UTC, reisdev requested changes

2022-05-12 14:50 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateApp/UI/Components/LoadingView.swift
> -        indicator.startAnimating()
Como não era requisito da tarefa, pode manter essa linha.

2022-05-12 19:02 UTC, reisdev requested changes

2022-05-12 19:02 UTC, reisdev commented on solutions/devsprint-matheus-reis-1/RealEstateApp/UI/Screens/PropertyList/PropertyListViewController.swift
> +
Complementando o ponto acima, como a `loadingView` não deve ser integrada ainda, o trecho abaixo deve ser removido

2022-05-12 19:47 UTC, reisdev approved these changes

2022-05-12 19:47 UTC, merged